In [1]:
import numpy as np
import numpy.linalg as LA
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
np.set_printoptions(precision=2)

# Define the matrix
A = np.array([[1, 2, 3, 4, 5],
              [2, 3, 4, 5, 6],
              [3, 4, 5, 6, 7],
              [4, 5, 6, 7, 8],
              [5, 6, 7, 8, 9]])

# Compute the SVD of the matrix
U, S, V = np.linalg.svd(A,full_matrices=True)

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(A)

# Print the rank of the matrix
print("Rank of matrix:\n", rank)
print("S: \n", S)

# Compute the four fundamental subspaces
row_space = U[:, :rank]
col_space = V[:, :rank]
null_space = V[:, rank:]
left_null_space = U[:, rank:]


print("U:\n", U)
print("Column space:\n", col_space)
print("Left null space:\n", left_null_space)
print("V.T:\n", V.T)
print("Row space:\n", row_space.T)
print("Right null space:\n", null_space.T)

Rank of matrix:
 2
S: 
 [2.69e+01 1.86e+00 8.37e-16 5.83e-16 4.43e-17]
U:
 [[-0.27 -0.73  0.55  0.31  0.04]
 [-0.35 -0.42 -0.29 -0.78 -0.07]
 [-0.43 -0.11 -0.65  0.46  0.42]
 [-0.51  0.19 -0.06  0.22 -0.81]
 [-0.59  0.5   0.44 -0.19  0.41]]
Column space:
 [[-0.27 -0.35]
 [ 0.73  0.42]
 [ 0.14 -0.29]
 [ 0.53 -0.77]
 [ 0.32  0.14]]
Left null space:
 [[ 0.55  0.31  0.04]
 [-0.29 -0.78 -0.07]
 [-0.65  0.46  0.42]
 [-0.06  0.22 -0.81]
 [ 0.44 -0.19  0.41]]
V.T:
 [[-0.27  0.73  0.14  0.53  0.32]
 [-0.35  0.42 -0.29 -0.77  0.14]
 [-0.43  0.11 -0.25  0.2  -0.84]
 [-0.51 -0.19  0.81 -0.19 -0.05]
 [-0.59 -0.5  -0.41  0.23  0.42]]
Row space:
 [[-0.27 -0.35 -0.43 -0.51 -0.59]
 [-0.73 -0.42 -0.11  0.19  0.5 ]]
Right null space:
 [[-0.43  0.11 -0.25  0.2  -0.84]
 [-0.51 -0.19  0.81 -0.19 -0.05]
 [-0.59 -0.5  -0.41  0.23  0.42]]


In [3]:
import numpy as np
X = np.random.rand(5,2)
U, S, V = np.linalg.svd(X,full_matrices=True)  # full SVD
Uhat, Shat, Vhat = np.linalg.svd(X,full_matrices=False) # economy SVD
print('U, S, V =')
U, S, V

U, S, V =


(array([[-0.34, -0.56, -0.46, -0.53, -0.29],
        [-0.45, -0.46,  0.01,  0.44,  0.62],
        [-0.42, -0.09,  0.84, -0.26, -0.21],
        [-0.58,  0.35, -0.23,  0.49, -0.5 ],
        [-0.4 ,  0.59, -0.17, -0.48,  0.48]]),
 array([1.97, 0.92]),
 array([[-0.75, -0.66],
        [-0.66,  0.75]]))

In [4]:
print('Uhat, Shat, Vhat = ')
Uhat, Shat, Vhat

Uhat, Shat, Vhat = 


(array([[-0.34, -0.56],
        [-0.45, -0.46],
        [-0.42, -0.09],
        [-0.58,  0.35],
        [-0.4 ,  0.59]]),
 array([1.97, 0.92]),
 array([[-0.75, -0.66],
        [-0.66,  0.75]]))

In [5]:
rr = np.linalg.matrix_rank(X)
print(f'rank of X = {rr}')

rank of X = 2


In [6]:
UTU = U.T@U
UUT = U@U.T
print('UUT, UTU = ')
UUT, UTU

UUT, UTU = 


(array([[ 1.00e+00,  8.76e-17,  1.03e-16,  2.99e-17,  6.02e-17],
        [ 8.76e-17,  1.00e+00, -3.75e-17, -1.90e-16, -2.22e-16],
        [ 1.03e-16, -3.75e-17,  1.00e+00,  1.05e-16,  1.19e-16],
        [ 2.99e-17, -1.90e-16,  1.05e-16,  1.00e+00,  3.15e-16],
        [ 6.02e-17, -2.22e-16,  1.19e-16,  3.15e-16,  1.00e+00]]),
 array([[ 1.00e+00, -1.82e-16,  3.24e-17,  1.83e-16,  1.09e-16],
        [-1.82e-16,  1.00e+00, -6.08e-17, -1.41e-16, -2.18e-16],
        [ 3.24e-17, -6.08e-17,  1.00e+00,  5.18e-17,  2.39e-17],
        [ 1.83e-16, -1.41e-16,  5.18e-17,  1.00e+00,  1.56e-16],
        [ 1.09e-16, -2.18e-16,  2.39e-17,  1.56e-16,  1.00e+00]]))

In [7]:
UhatUhatT = Uhat@Uhat.T
UhatTUhat = Uhat.T@Uhat
print('UhatUhatT, UhatTUhat= ')
UhatUhatT, UhatTUhat

UhatUhatT, UhatTUhat= 


(array([[ 0.43,  0.41,  0.19,  0.  , -0.19],
        [ 0.41,  0.42,  0.23,  0.1 , -0.09],
        [ 0.19,  0.23,  0.19,  0.22,  0.12],
        [ 0.  ,  0.1 ,  0.22,  0.46,  0.44],
        [-0.19, -0.09,  0.12,  0.44,  0.51]]),
 array([[ 1.00e+00, -1.82e-16],
        [-1.82e-16,  1.00e+00]]))

In [8]:
import numpy as np
X = np.random.rand(2,5)
U, S, V = np.linalg.svd(X,full_matrices=True)  # full SVD
Uhat, Shat, Vhat = np.linalg.svd(X,full_matrices=False) # economy SVD
print('U, S, V = ')
U, S, V

U, S, V = 


(array([[-0.92, -0.39],
        [-0.39,  0.92]]),
 array([2.24, 0.64]),
 array([[-3.61e-01, -4.17e-01, -4.01e-01, -4.51e-01, -5.76e-01],
        [-1.45e-04, -5.24e-01, -4.07e-01, -1.00e-01,  7.42e-01],
        [-3.18e-01, -4.81e-01,  8.03e-01, -1.22e-01,  8.41e-02],
        [-4.39e-01, -2.14e-01, -1.59e-01,  8.49e-01, -1.24e-01],
        [-7.59e-01,  5.24e-01, -5.34e-02, -2.25e-01,  3.10e-01]]))

In [9]:
print('Uhat, Shat, Vhat = ')
Uhat, Shat, Vhat

Uhat, Shat, Vhat = 


(array([[-0.92, -0.39],
        [-0.39,  0.92]]),
 array([2.24, 0.64]),
 array([[-3.61e-01, -4.17e-01, -4.01e-01, -4.51e-01, -5.76e-01],
        [-1.45e-04, -5.24e-01, -4.07e-01, -1.00e-01,  7.42e-01]]))

In [10]:
SShat=np.diag(Shat)
np.allclose(X, Uhat@SShat@Vhat)

True

In [11]:
class DecomAnalysis:
    """
    A class for conducting PCA and SVD.
    """

    def __init__(self, X, n_component=None):

        self.X = X

        self.Ω = (X @ X.T)

        self.m, self.n = X.shape
        self.r = LA.matrix_rank(X)

        if n_component:
            self.n_component = n_component
        else:
            self.n_component = self.m

    def pca(self):

        𝜆, P = LA.eigh(self.Ω)    # columns of P are eigenvectors

        ind = sorted(range(𝜆.size), key=lambda x: 𝜆[x], reverse=True)

        # sort by eigenvalues
        self.𝜆 = 𝜆[ind]
        P = P[:, ind]
        self.P = P @ diag_sign(P)

        self.Λ = np.diag(self.𝜆)

        self.explained_ratio_pca = np.cumsum(self.𝜆) / self.𝜆.sum()

        # compute the N by T matrix of principal components
        self.𝜖 = self.P.T @ self.X

        P = self.P[:, :self.n_component]
        𝜖 = self.𝜖[:self.n_component, :]

        # transform data
        self.X_pca = P @ 𝜖

    def svd(self):

        U, 𝜎, VT = LA.svd(self.X)

        ind = sorted(range(𝜎.size), key=lambda x: 𝜎[x], reverse=True)

        # sort by eigenvalues
        d = min(self.m, self.n)

        self.𝜎 = 𝜎[ind]
        U = U[:, ind]
        D = diag_sign(U)
        self.U = U @ D
        VT[:d, :] = D @ VT[ind, :]
        self.VT = VT

        self.Σ = np.zeros((self.m, self.n))
        self.Σ[:d, :d] = np.diag(self.𝜎)

        𝜎_sq = self.𝜎 ** 2
        self.explained_ratio_svd = np.cumsum(𝜎_sq) / 𝜎_sq.sum()

        # slicing matrices by the number of components to use
        U = self.U[:, :self.n_component]
        Σ = self.Σ[:self.n_component, :self.n_component]
        VT = self.VT[:self.n_component, :]

        # transform data
        self.X_svd = U @ Σ @ VT

    def fit(self, n_component):

        # pca
        P = self.P[:, :n_component]
        𝜖 = self.𝜖[:n_component, :]

        # transform data
        self.X_pca = P @ 𝜖

        # svd
        U = self.U[:, :n_component]
        Σ = self.Σ[:n_component, :n_component]
        VT = self.VT[:n_component, :]

        # transform data
        self.X_svd = U @ Σ @ VT

def diag_sign(A):
    "Compute the signs of the diagonal of matrix A"

    D = np.diag(np.sign(np.diag(A)))

    return D

In [12]:
def compare_pca_svd(da):
    """
    Compare the outcomes of PCA and SVD.
    """

    da.pca()
    da.svd()

    print('Eigenvalues and Singular values\n')
    print(f'λ = {da.λ}\n')
    print(f'σ^2 = {da.σ**2}\n')
    print('\n')

    # loading matrices
    fig, axs = plt.subplots(1, 2, figsize=(14, 5))
    plt.suptitle('loadings')
    axs[0].plot(da.P.T)
    axs[0].set_title('P')
    axs[0].set_xlabel('m')
    axs[1].plot(da.U.T)
    axs[1].set_title('U')
    axs[1].set_xlabel('m')
    plt.show()

    # principal components
    fig, axs = plt.subplots(1, 2, figsize=(14, 5))
    plt.suptitle('principal components')
    axs[0].plot(da.ε.T)
    axs[0].set_title('ε')
    axs[0].set_xlabel('n')
    axs[1].plot(da.VT[:da.r, :].T * np.sqrt(da.λ))
    axs[1].set_title('$V^\top *\sqrt{\lambda}$')
    axs[1].set_xlabel('n')
    plt.show()